### PR TITLE
Suggestion box added

### PR DESCRIPTION
**Pull request by saurabh28march**
Screenshot (30)
Screenshot (31)

### CODE REVIEW

**Comment by saurabh28march** [comment]
@maze-runnar   review it.

**Comment by maze-runnar** [comment]
> @maze-runnar review it.
@saurabh28march  text is not visible on selecting. Use a different color.
Screenshot from 2020-08-08 16-55-50

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH please merge after requested changes are done!!

**Comment by maze-runnar** [comment]
Screenshot from 2020-08-08 17-11-20
Screenshot from 2020-08-08 17-11-24

Wrong value in input box, use` " "` instead of `' '` to prevent such error in data.

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH merge please

**Pull request merged**
