### PR TITLE
Added search functionality

### PR DESCRIPTION
**Pull request by saurabh28march**
- Made changes in app.py
-Created explore.html to implement this new  feature

### CODE REVIEW

**Comment by saurabh28march** [comment]
@maze-runnar @SARTHAK1SINGH please review and merge !!

**Comment by maze-runnar** [comment]
@saurabh28march include `newsapi-python==0.2.6` in requirements, else if fine..

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH after @saurabh28march completed rewquire changes enhance it's UI soon

**Comment by maze-runnar** [comment]
@saurabh28march  add voice enable search on every search page in project.

**Comment by maze-runnar** [comment]
And @SARTHAK1SINGH add a drop down here too like main page to get data from dataset, twitter and newsAPI

**Comment by maze-runnar** [comment]
@saurabh28march add date to this PR
```
 <label for="fromdate">From</label>
  <input type="date" id="fromdate" class="form-control" name="birthday">
```


and add this in explore function in app.py

```
@app.route("/explore",methods=['GET','POST'])
def  explore():
    if request.method == 'POST':
        search_word=request.form['search_query']
        date_from = request.form['birthday']
        print(search_word)
        print(date_from)
        top_headlines = newsapi.get_everything(q=search_word,sort_by='relevancy',language='en',from_param=str(date_from),)
        count_of_headlines=top_headlines['totalResults']
        count_of_headlines=int(count_of_headlines)
        title_list=[]
        description_list=[]
        urls_headlines=[]

        for headline in top_headlines['articles']:
            title_list.append(headline['title'])
            description_list.append(headline['description'])
            urls_headlines.append(headline['url'])


        total_elements=[]
        for i in range(len(title_list)):
            total_elements.append(i)
        print(total_elements)

        return render_template('explore.html',title_list=title_list,description_list=description_list,
        urls_headlines=urls_headlines,total_elements=total_elements)

    else:
        if request.method=='GET':
            return render_template("explore.html")


```

**Comment by maze-runnar** [comment]
then resulting working UI will be
Screenshot from 2020-08-31 11-12-52

**Comment by saurabh28march** [comment]
> @saurabh28march add date to this PR
> 
> ```
>  <label for="fromdate">From</label>
>   <input type="date" id="fromdate" class="form-control" name="birthday">
> ```
> 
> and add this in explore function in app.py
> 
> ```
> @app.route("/explore",methods=['GET','POST'])
> def  explore():
>     if request.method == 'POST':
>         search_word=request.form['search_query']
>         date_from = request.form['birthday']
>         print(search_word)
>         print(date_from)
>         top_headlines = newsapi.get_everything(q=search_word,sort_by='relevancy',language='en',from_param=str(date_from),)
>         count_of_headlines=top_headlines['totalResults']
>         count_of_headlines=int(count_of_headlines)
>         title_list=[]
>         description_list=[]
>         urls_headlines=[]
> 
>         for headline in top_headlines['articles']:
>             title_list.append(headline['title'])
>             description_list.append(headline['description'])
>             urls_headlines.append(headline['url'])
> 
> 
>         total_elements=[]
>         for i in range(len(title_list)):
>             total_elements.append(i)
>         print(total_elements)
> 
>         return render_template('explore.html',title_list=title_list,description_list=description_list,
>         urls_headlines=urls_headlines,total_elements=total_elements)
> 
>     else:
>         if request.method=='GET':
>             return render_template("explore.html")
> ```

We cannot fetch data for more than one month using this api

**Comment by maze-runnar** [comment]
still I need a date

**Comment by saurabh28march** [comment]
> still I need a date

It will give error if date is passed in the parameter for more than on month. I have already checked this problem

**Comment by maze-runnar** [comment]
ok, so is there any solution

**Comment by saurabh28march** [comment]
> @saurabh28march add voice enable search on every search page in project.

I will work on it.

**Comment by maze-runnar** [comment]
you are good to go

**Comment by saurabh28march** [comment]
> ok, so is there any solution

yes, if only we can restrict the user not to enter date more than a month

**Comment by maze-runnar** [comment]
> > ok, so is there any solution
> 
> yes, if only we can restrict the user not to enter date more than a month

ok I am doing this, setting min to one month before :+1:

**Comment by saurabh28march** [comment]
> > > ok, so is there any solution
> > 
> > 
> > yes, if only we can restrict the user not to enter date more than a month
> 
> ok I am doing this, setting min to one month before 👍

ok go ahead.

**Pull request merged**
