### PR TITLE
Voice interaction added

### PR DESCRIPTION
**Pull request by SARTHAK1SINGH**

### CODE REVIEW

**Comment by SARTHAK1SINGH** [comment]
check it @maze-runnar  @saurabh28march  on your system and approve if it's working fine

**Comment by maze-runnar** [comment]
I think this kind of help syntax is enough on index page -
Screenshot from 2020-08-18 08-11-29

**Comment by maze-runnar** [comment]
@saurabh28march create that PR for audio_intro part.

**Comment by maze-runnar** [comment]
What about a HELP modal ??
Screenshot from 2020-08-18 08-41-23

**Pull request merged**
