### PR TITLE
sentiment analysis of tweets and tweets preprocessing

### PR DESCRIPTION
**Pull request by maze-runnar**
@SARTHAK1SINGH @saurabh28march please review.

### CODE REVIEW

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH please enhance UI now with tables and give proper font and cards so that user don't have to scroll a long way down.

**Comment by maze-runnar** [comment]
@saurabh28march show this kind of graph on this page to show change in sentiments over time.

**Comment by maze-runnar** [comment]
please both of you try to make these changes fast.

**Review by saurabh28march — COMMENTED** [review]
**It's giving error for the input :**
Screenshot (124)
Screenshot (123)

**Comment by maze-runnar** [comment]
ok looking it

**Comment by maze-runnar** [comment]
@saurabh28march please check now

**Comment by saurabh28march** [comment]
@SARTHAK1SINGH  merge..

**Comment by SARTHAK1SINGH** [comment]
Awesome work by Sundaram Dubey <br>
iske 1000 $ se type ```` 50$ ki party ```` 😄

**Pull request merged**
