### PR TITLE
implementing Download result as PDF

### PR DESCRIPTION
**Pull request by maze-runnar**
how it looks :
[MedsResult.pdf](https://github.com/SARTHAK1SINGH/HackthonFB/files/5083974/MedsResult.pdf)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@saurabh28march test it asap.

**Comment by SARTHAK1SINGH** [comment]
make the colours more dark or make background black like UI

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH please review

**Comment by maze-runnar** [comment]
> @maze-runnar it is not showing results for most negative and most positive review paragraph at the end of pdf

it could be due to browser difference. @SARTHAK1SINGH please confirm.

**Comment by SARTHAK1SINGH** [comment]
now it's working fine 💯

**Pull request merged**
