### PR TITLE
adding twiter scrap with date to explore page

### PR DESCRIPTION
**Pull request by maze-runnar**

### CODE REVIEW

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH make ui of this page more robust. Make those boxes small by making font small and add 4 or 3 boxes in a row.

**Comment by maze-runnar** [comment]
@saurabh28march  review please

**Comment by maze-runnar** [comment]
please describe the final changes that need to be made before hosting

**Review by saurabh28march — CHANGES_REQUESTED** [review]
- After clicking  search button ,help section automatically popup, I think that should be removed.

- After clicking  search button the value in date section changes to dd-mm-yyyy , the original date entered   by user should retain as long as page is not reloaded.

**Screenshot of Just before clicking search button**
Screenshot (122)

**Screenshot of Just after clicking search button**
Screenshot (120)

Screenshot (121)

Other than that twitter scrap is working fine... @maze-runnar

**Comment by maze-runnar** [comment]
> After clicking search button ,help section automatically popup, I think that should be removed.

this one is done.

> After clicking search button the value in date section changes to dd-mm-yyyy , the original date entered by user should retain as long as page is not reloaded.

Not a priority

**Comment by saurabh28march** [comment]
> > After clicking search button ,help section automatically popup, I think that should be removed.
> 
> this one is done.
> 
> > After clicking search button the value in date section changes to dd-mm-yyyy , the original date entered by user should retain as long as page is not reloaded.
> 
> Not a priority

ok, date issue can be resolved in later stages @SARTHAK1SINGH  please merge.

**Review by saurabh28march — APPROVED** [review]

**Pull request merged**
